In [1]:
import numpy as np

dizi = np.arange(10)  
print(dizi)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
numpydizi = np.zeros((3, 4))
numpydizi


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
numpydizi2 = np.ones((2, 3))
numpydizi2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
dizi = np.arange(12)
dizi=dizi.reshape(3, 4)
print("Dizi:",dizi)
print("boyut:", dizi.shape)
print("Size:", dizi.size)
print("Ndim:", dizi.ndim)

Dizi: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
boyut: (3, 4)
Size: 12
Ndim: 2


In [10]:

liste = [10, 20, 30, 40]

dizi1 = np.array(liste, dtype=np.int64)

print(dizi1)
print("Veri tipi:", dizi1.dtype)

[10 20 30 40]
Veri tipi: int64


In [11]:
dizi2 = np.arange(20)

yeni_dizi = dizi2[(dizi2 > 5) & (dizi2 < 15)]

print(yeni_dizi)

[ 6  7  8  9 10 11 12 13 14]


In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a:",a)
print("b:",b)

a: [1 2 3]
b: [4 5 6]


In [16]:
print("Toplam:", a+b)
print("Çarpım:", a*b)

Toplam: [5 7 9]
Çarpım: [ 4 10 18]


In [18]:
M = np.arange(1, 26)
M=M.reshape(5, 5)
M

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
print("İkinci Satır:", M[1] )
print("Üçüncü Sütun:", M[:, 2] )

İkinci Satır: [ 6  7  8  9 10]
Üçüncü Sütun: [ 3  8 13 18 23]


In [24]:
matris = np.random.randint(0, 10, (3, 2))
print("Matris:",matris)

satir = len(matris)
sutun = len(matris[0])

transpoz = []

for j in range(sutun):
    yeni_satir = []
    for i in range(satir):
        yeni_satir.append(matris[i][j])
    transpoz.append(yeni_satir)

print("Transpoz:",np.array(transpoz))

Matris: [[7 5]
 [8 5]
 [7 8]]
Transpoz: [[7 8 7]
 [5 5 8]]


In [27]:
dizi3 = np.array([1, 2, np.nan, 4, 5, np.nan, 7])

nanSayisi = np.isnan(dizi3).sum()

print("NaN sayısı:", nanSayisi)

NaN sayısı: 2


In [28]:
M = np.random.randint(1, 100, (5, 5))
print("Matris:\n", M)
print("Ortalama:", M.mean())
print("En büyük değer:",M.max())
std_sutun = M.std(axis=0)
print("Sütun bazında standart sapma:", std_sutun)

Matris:
 [[ 2 80 89 97  1]
 [38 54 23 86 38]
 [71 98 94 61 60]
 [58 10 82 90 30]
 [35 18 41 26 44]]
Ortalama: 53.04
En büyük değer: 98
Sütun bazında standart sapma: [23.47253714 34.12916641 28.43518947 26.00769117 19.46894964]


In [29]:
a = np.array([1, 2])
b = np.array([3, 4])

yatay = np.hstack([a, b])
print("Yatay:", yatay)

dikey = np.vstack([a, b])
print("Dikey:\n", dikey)

Yatay: [1 2 3 4]
Dikey:
 [[1 2]
 [3 4]]


In [30]:
matris = np.random.randint(0, 100, (5, 5))
ortalama = np.mean(matris)
max_deger = np.max(matris)
std_sutun = np.std(matris, axis=0)

print(matris)
print(ortalama)
print(max_deger)
print(std_sutun)

[[79 87 67 13 73]
 [68 36 90 45 40]
 [49 84 27 73 15]
 [ 7 49 36 18 82]
 [57 18 61 73  9]]
50.24
90
[24.67387282 26.94735609 22.55127491 25.76509266 29.55266485]


In [31]:
b = np.array([3, 4])

yatay = np.hstack((a, b))
dikey = np.vstack((a, b))

print(yatay)
print(dikey)

[1 2 3 4]
[[1 2]
 [3 4]]


In [32]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

sonuc = A.dot(B)
print(sonuc)

[[19 22]
 [43 50]]


In [35]:

matris = np.random.randint(0, 100, (5, 5)) 
matris


array([[24, 66, 85,  3, 83],
       [43, 36, 95, 90, 84],
       [40, 59, 49, 42, 75],
       [94,  9, 85, 47, 79],
       [ 8, 94, 15, 46, 25]], dtype=int32)